//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.13

pub use super::global_materials::Entity as GlobalMaterials;
pub use super::global_recipes::Entity as GlobalRecipes;
pub use super::users::Entity as Users;
